[cite_start]name: Docker CI/CD [cite: 56]
on:
  push:
    branches:
      - [cite_start]feature/add-test [cite: 58, 59, 60]
jobs:
  build-and-push:
    [cite_start]runs-on: ubuntu-latest [cite: 63]
    steps:
      - [cite_start]name: Checkout code [cite: 65]
        [cite_start]uses: actions/checkout@v2 [cite: 66]

      - [cite_start]name: Login to Docker Hub [cite: 67]
        [cite_start]uses: docker/login-action@v1 [cite: 68]
        with:
          [cite_start]username: ${{ secrets.DOCKER_USERNAME }} [cite: 70]
          [cite_start]password: ${{ secrets.DOCKER_TOKEN }} [cite: 71]

      - [cite_start]name: Build and push Docker image [cite: 72]
        [cite_start]uses: docker/build-push-action@v2 [cite: 73]
        with:
          [cite_start]context: . [cite: 75]
          [cite_start]push: true [cite: 76]
          tags: |
             docker login -u iamkrk11/sample-node-project:latest [cite: 78]
             docker login -u iamkrk11/sample-node-project:${{ github.sha }} [cite: 79]